codecov:
  token: # Not required for public repositories
  bot: codecov[bot]
  ci:
    - github-actions

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
        branches:
          - main
          - master
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - src/mgt7_pdf_to_json/
    carryforward: true

ignore:
  - "*/tests/*"
  - "*/test_*.py"
  - "*/__pycache__/*"
  - "*/__init__.py"
  - "*/__main__.py"
